# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findMaxMean <- function(num, binNum, lengthNum) {
    .Call('_m6Ascan_findMaxMean', PACKAGE = 'm6Ascan', num, binNum, lengthNum)
}

rcpp_hello <- function() {
    .Call('_m6Ascan_rcpp_hello', PACKAGE = 'm6Ascan')
}

